### ISSUE TITLE
Supporting addition/averaging in color spaces other than RGB

### ISSUE THREAD

**Issue by jiningq** [JuliaLang/Color.jl#106]
According to this question
http://stackoverflow.com/questions/649454/what-is-the-best-way-to-average-two-colors-that-define-a-linear-gradient
it seems LAB is the most appropriate space to do color averaging in. Yet it seems averaging isn't supported in that space. I'm wondering whether we can add support for that.

Or, this could possibly be very silly, is there a way I can access the color coordinate of type LAB so I can do operations on these numeric values directly.

**Comment by timholy** [comment]
This package is deprecated.
