### ISSUE TITLE
Wrong value in colormap("Grays") 

### ISSUE THREAD

**Issue by tknopp** [JuliaLang/Color.jl#59]
As Tim observed in #58, the gray colormap has a wrong last value that contains NaNs instead of zeros. This used to work at a former version of Color.jl

```
julia> Color.colormap("Grays",4)
4-element Array{RGB{Float64},1}:
 RGB{Float64}(1.0,0.9999999843772079,0.9999999986434457)                  
 RGB{Float64}(0.8022332446272299,0.8022332107836624,0.8022332223755984)   
 RGB{Float64}(0.48514909922353305,0.48514907789844725,0.48514908520261363)
 RGB{Float64}(NaN,NaN,NaN)  
```

**Comment by ikirill** [comment]
Still present in current git version, with nightly julia version:

    julia> Color.colormap("Grays", 4)
    4-element Array{Color.RGB{Float64},1}:
     Color.RGB{Float64}(1.0,0.9999999843772079,0.9999999986434464)
     Color.RGB{Float64}(0.8022332446272302,0.8022332107836626,0.8022332223756009)
     Color.RGB{Float64}(NaN,NaN,NaN)
     Color.RGB{Float64}(0.0,0.0,0.0)

**Comment by jiahao** [comment]
I've traced it down to the following bug:

```jl
julia> p = Color.LCHuv{Float64}(0.0,0.0,0.0); 1.0p 
Color.LCHuv{Float64}(0.0,NaN,NaN)
```
