### ISSUE TITLE
convert error

### ISSUE THREAD

**Issue by bjarthur** [JuliaLang/Color.jl#68]
with julia 0.3.1 on windows 7

```
julia> using Color

julia> { 1 => (1,1,1,1,1,1,1,1,1.,false) }
Dict{Any,Any} with 1 entry:
  1 => (1,1,1,1,1,1,1,1,1.0,false)

julia> convert((Int...), (uint(1),))
ERROR: `convert` has no method matching convert(::Type{Int64...}, ::Uint64)
 in convert at base.jl:13
```

this is fixed if i simply ```Pkg.pin("Color",v"0.3.9")```

likely related to https://github.com/JuliaLang/julia/issues/8631 and https://github.com/timholy/HDF5.jl/issues/160

**Comment by jiahao** [comment]
Closed by #73
