### ISSUE TITLE
test coverage % incorrect?

### ISSUE THREAD

**Issue by catawbasam** [JuliaLang/Color.jl#79]
The coverage badge reports '0', despite numerous tests in /test.
Perhaps the tests aren't being fired off?

**Comment by jiahao** [comment]
#108 updated the Travis CI configuration but the default probably does not produce any coverage data.

**Comment by timholy** [comment]
Bizarre:
https://github.com/JuliaLang/Color.jl/blob/b868a112144dbe7a66429124b8cfcb4ab52765be/.travis.yml#L10

and
https://travis-ci.org/JuliaLang/Color.jl/jobs/50709224

which seem to indicate coverage ran just fine.

**Comment by timholy** [comment]
Ah, the .cov files are just not being generated.
