### ISSUE TITLE
LoadError: UndefVarError: Graphics not defined

### ISSUE THREAD

**Issue by scidom** [JuliaLang/Color.jl#84]
Does anyone else encounter the following error with Julia v0.4?

```
ERROR: LoadError: UndefVarError: Graphics not defined
 in include at ./boot.jl:249
 in include_from_node1 at ./loading.jl:128
 in reload_path at ./loading.jl:152
 in _require at ./loading.jl:67
 in require at ./loading.jl:52
while loading /home/theodore/.julia/v0.4/Color/src/Color.jl, in expression starting on line 8
```

**Comment by jiahao** [comment]
`Graphics` was recently removed from `Base`. Try updating your version of `Color.jl`.

**Comment by scidom** [comment]
Thanks @jiahao, I tried `Pkg.update()` and I get the same error - do you mean I should try to `Pkg.checkout("Color")`?

**Comment by scidom** [comment]
Hm, interesting... I removed my "~/.julia/v0.4" and reinstalled only `Color.jl`, then `using Color` worked fine. After this, I installed again all the packages that I usually use and I got the same error as above, so there seems to be some inter-dependency issue between `Color` and one of the other packages I installed. Here is the complete list of packages I installed after `Color`:

```pkgs = [
  "IJulia",
  "Sundials",
  "DSP",
  "Gadfly",
  "DataFrames",
  "DataFramesMeta",
  "MPI",
  "Graphs",
  "Mamba",
  "Lora",
  "ChemicalKinetics"
]

for p in pkgs; Pkg.add(p); end
```

**Comment by scidom** [comment]
Ah, I tried them one by one. It is `Mamba` that causes the conflict, once I removed it (while keeping all the rest of packages), `using Color` works again. Cheers, I will close this issue since it is not Color-endemic.

**Comment by jiahao** [comment]
Perhaps you could ask the authors of `Mamba` why `Color` is pinned to a specific version, and if there was a bug in newer versions, if that has been fixed.

**Comment by scidom** [comment]
I cross-referenced it @jiahao.
